// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/company/Workload.proto

package com.company;

public final class WorkloadProto {
  private WorkloadProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface WorkloadOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Workload)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 cpuUtil = 1;</code>
     * @return The cpuUtil.
     */
    int getCpuUtil();

    /**
     * <code>int32 networkIn = 2;</code>
     * @return The networkIn.
     */
    int getNetworkIn();

    /**
     * <code>int32 networkOut = 3;</code>
     * @return The networkOut.
     */
    int getNetworkOut();

    /**
     * <code>int32 memUtil = 4;</code>
     * @return The memUtil.
     */
    int getMemUtil();
  }
  /**
   * Protobuf type {@code Workload}
   */
  public static final class Workload extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Workload)
      WorkloadOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Workload.newBuilder() to construct.
    private Workload(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Workload() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Workload();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Workload(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              cpuUtil_ = input.readInt32();
              break;
            }
            case 16: {

              networkIn_ = input.readInt32();
              break;
            }
            case 24: {

              networkOut_ = input.readInt32();
              break;
            }
            case 32: {

              memUtil_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.company.WorkloadProto.internal_static_Workload_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.company.WorkloadProto.internal_static_Workload_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.company.WorkloadProto.Workload.class, com.company.WorkloadProto.Workload.Builder.class);
    }

    public static final int CPUUTIL_FIELD_NUMBER = 1;
    private int cpuUtil_;
    /**
     * <code>int32 cpuUtil = 1;</code>
     * @return The cpuUtil.
     */
    @java.lang.Override
    public int getCpuUtil() {
      return cpuUtil_;
    }

    public static final int NETWORKIN_FIELD_NUMBER = 2;
    private int networkIn_;
    /**
     * <code>int32 networkIn = 2;</code>
     * @return The networkIn.
     */
    @java.lang.Override
    public int getNetworkIn() {
      return networkIn_;
    }

    public static final int NETWORKOUT_FIELD_NUMBER = 3;
    private int networkOut_;
    /**
     * <code>int32 networkOut = 3;</code>
     * @return The networkOut.
     */
    @java.lang.Override
    public int getNetworkOut() {
      return networkOut_;
    }

    public static final int MEMUTIL_FIELD_NUMBER = 4;
    private int memUtil_;
    /**
     * <code>int32 memUtil = 4;</code>
     * @return The memUtil.
     */
    @java.lang.Override
    public int getMemUtil() {
      return memUtil_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (cpuUtil_ != 0) {
        output.writeInt32(1, cpuUtil_);
      }
      if (networkIn_ != 0) {
        output.writeInt32(2, networkIn_);
      }
      if (networkOut_ != 0) {
        output.writeInt32(3, networkOut_);
      }
      if (memUtil_ != 0) {
        output.writeInt32(4, memUtil_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (cpuUtil_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, cpuUtil_);
      }
      if (networkIn_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, networkIn_);
      }
      if (networkOut_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, networkOut_);
      }
      if (memUtil_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, memUtil_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.company.WorkloadProto.Workload)) {
        return super.equals(obj);
      }
      com.company.WorkloadProto.Workload other = (com.company.WorkloadProto.Workload) obj;

      if (getCpuUtil()
          != other.getCpuUtil()) return false;
      if (getNetworkIn()
          != other.getNetworkIn()) return false;
      if (getNetworkOut()
          != other.getNetworkOut()) return false;
      if (getMemUtil()
          != other.getMemUtil()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CPUUTIL_FIELD_NUMBER;
      hash = (53 * hash) + getCpuUtil();
      hash = (37 * hash) + NETWORKIN_FIELD_NUMBER;
      hash = (53 * hash) + getNetworkIn();
      hash = (37 * hash) + NETWORKOUT_FIELD_NUMBER;
      hash = (53 * hash) + getNetworkOut();
      hash = (37 * hash) + MEMUTIL_FIELD_NUMBER;
      hash = (53 * hash) + getMemUtil();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.company.WorkloadProto.Workload parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.company.WorkloadProto.Workload parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.company.WorkloadProto.Workload parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.company.WorkloadProto.Workload parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.company.WorkloadProto.Workload parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.company.WorkloadProto.Workload parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.company.WorkloadProto.Workload parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.company.WorkloadProto.Workload parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.company.WorkloadProto.Workload parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.company.WorkloadProto.Workload parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.company.WorkloadProto.Workload parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.company.WorkloadProto.Workload parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.company.WorkloadProto.Workload prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Workload}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Workload)
        com.company.WorkloadProto.WorkloadOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.company.WorkloadProto.internal_static_Workload_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.company.WorkloadProto.internal_static_Workload_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.company.WorkloadProto.Workload.class, com.company.WorkloadProto.Workload.Builder.class);
      }

      // Construct using com.company.WorkloadProto.Workload.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        cpuUtil_ = 0;

        networkIn_ = 0;

        networkOut_ = 0;

        memUtil_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.company.WorkloadProto.internal_static_Workload_descriptor;
      }

      @java.lang.Override
      public com.company.WorkloadProto.Workload getDefaultInstanceForType() {
        return com.company.WorkloadProto.Workload.getDefaultInstance();
      }

      @java.lang.Override
      public com.company.WorkloadProto.Workload build() {
        com.company.WorkloadProto.Workload result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.company.WorkloadProto.Workload buildPartial() {
        com.company.WorkloadProto.Workload result = new com.company.WorkloadProto.Workload(this);
        result.cpuUtil_ = cpuUtil_;
        result.networkIn_ = networkIn_;
        result.networkOut_ = networkOut_;
        result.memUtil_ = memUtil_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.company.WorkloadProto.Workload) {
          return mergeFrom((com.company.WorkloadProto.Workload)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.company.WorkloadProto.Workload other) {
        if (other == com.company.WorkloadProto.Workload.getDefaultInstance()) return this;
        if (other.getCpuUtil() != 0) {
          setCpuUtil(other.getCpuUtil());
        }
        if (other.getNetworkIn() != 0) {
          setNetworkIn(other.getNetworkIn());
        }
        if (other.getNetworkOut() != 0) {
          setNetworkOut(other.getNetworkOut());
        }
        if (other.getMemUtil() != 0) {
          setMemUtil(other.getMemUtil());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.company.WorkloadProto.Workload parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.company.WorkloadProto.Workload) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int cpuUtil_ ;
      /**
       * <code>int32 cpuUtil = 1;</code>
       * @return The cpuUtil.
       */
      @java.lang.Override
      public int getCpuUtil() {
        return cpuUtil_;
      }
      /**
       * <code>int32 cpuUtil = 1;</code>
       * @param value The cpuUtil to set.
       * @return This builder for chaining.
       */
      public Builder setCpuUtil(int value) {
        
        cpuUtil_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 cpuUtil = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearCpuUtil() {
        
        cpuUtil_ = 0;
        onChanged();
        return this;
      }

      private int networkIn_ ;
      /**
       * <code>int32 networkIn = 2;</code>
       * @return The networkIn.
       */
      @java.lang.Override
      public int getNetworkIn() {
        return networkIn_;
      }
      /**
       * <code>int32 networkIn = 2;</code>
       * @param value The networkIn to set.
       * @return This builder for chaining.
       */
      public Builder setNetworkIn(int value) {
        
        networkIn_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 networkIn = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearNetworkIn() {
        
        networkIn_ = 0;
        onChanged();
        return this;
      }

      private int networkOut_ ;
      /**
       * <code>int32 networkOut = 3;</code>
       * @return The networkOut.
       */
      @java.lang.Override
      public int getNetworkOut() {
        return networkOut_;
      }
      /**
       * <code>int32 networkOut = 3;</code>
       * @param value The networkOut to set.
       * @return This builder for chaining.
       */
      public Builder setNetworkOut(int value) {
        
        networkOut_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 networkOut = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearNetworkOut() {
        
        networkOut_ = 0;
        onChanged();
        return this;
      }

      private int memUtil_ ;
      /**
       * <code>int32 memUtil = 4;</code>
       * @return The memUtil.
       */
      @java.lang.Override
      public int getMemUtil() {
        return memUtil_;
      }
      /**
       * <code>int32 memUtil = 4;</code>
       * @param value The memUtil to set.
       * @return This builder for chaining.
       */
      public Builder setMemUtil(int value) {
        
        memUtil_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 memUtil = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearMemUtil() {
        
        memUtil_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Workload)
    }

    // @@protoc_insertion_point(class_scope:Workload)
    private static final com.company.WorkloadProto.Workload DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.company.WorkloadProto.Workload();
    }

    public static com.company.WorkloadProto.Workload getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Workload>
        PARSER = new com.google.protobuf.AbstractParser<Workload>() {
      @java.lang.Override
      public Workload parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Workload(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Workload> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Workload> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.company.WorkloadProto.Workload getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Workload_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Workload_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032com/company/Workload.proto\"S\n\010Workload" +
      "\022\017\n\007cpuUtil\030\001 \001(\005\022\021\n\tnetworkIn\030\002 \001(\005\022\022\n\n" +
      "networkOut\030\003 \001(\005\022\017\n\007memUtil\030\004 \001(\005B\034\n\013com" +
      ".companyB\rWorkloadProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Workload_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Workload_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Workload_descriptor,
        new java.lang.String[] { "CpuUtil", "NetworkIn", "NetworkOut", "MemUtil", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
