// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: main/java/workload/Workload.proto

package workload;

public final class WorkloadProto {
  private WorkloadProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface clientRFWOrBuilder extends
      // @@protoc_insertion_point(interface_extends:java.clientRFW)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 RFWId = 1;</code>
     * @return The rFWId.
     */
    int getRFWId();

    /**
     * <code>int32 benchType = 2;</code>
     * @return The benchType.
     */
    int getBenchType();

    /**
     * <code>int32 workLoad = 3;</code>
     * @return The workLoad.
     */
    int getWorkLoad();

    /**
     * <code>int32 batchUnit = 4;</code>
     * @return The batchUnit.
     */
    int getBatchUnit();

    /**
     * <code>int32 batchId = 5;</code>
     * @return The batchId.
     */
    int getBatchId();

    /**
     * <code>int32 batchSize = 6;</code>
     * @return The batchSize.
     */
    int getBatchSize();
  }
  /**
   * Protobuf type {@code java.clientRFW}
   */
  public static final class clientRFW extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:java.clientRFW)
      clientRFWOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use clientRFW.newBuilder() to construct.
    private clientRFW(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private clientRFW() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new clientRFW();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private clientRFW(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              rFWId_ = input.readInt32();
              break;
            }
            case 16: {

              benchType_ = input.readInt32();
              break;
            }
            case 24: {

              workLoad_ = input.readInt32();
              break;
            }
            case 32: {

              batchUnit_ = input.readInt32();
              break;
            }
            case 40: {

              batchId_ = input.readInt32();
              break;
            }
            case 48: {

              batchSize_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return workload.WorkloadProto.internal_static_java_clientRFW_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return workload.WorkloadProto.internal_static_java_clientRFW_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              workload.WorkloadProto.clientRFW.class, workload.WorkloadProto.clientRFW.Builder.class);
    }

    public static final int RFWID_FIELD_NUMBER = 1;
    private int rFWId_;
    /**
     * <code>int32 RFWId = 1;</code>
     * @return The rFWId.
     */
    @java.lang.Override
    public int getRFWId() {
      return rFWId_;
    }

    public static final int BENCHTYPE_FIELD_NUMBER = 2;
    private int benchType_;
    /**
     * <code>int32 benchType = 2;</code>
     * @return The benchType.
     */
    @java.lang.Override
    public int getBenchType() {
      return benchType_;
    }

    public static final int WORKLOAD_FIELD_NUMBER = 3;
    private int workLoad_;
    /**
     * <code>int32 workLoad = 3;</code>
     * @return The workLoad.
     */
    @java.lang.Override
    public int getWorkLoad() {
      return workLoad_;
    }

    public static final int BATCHUNIT_FIELD_NUMBER = 4;
    private int batchUnit_;
    /**
     * <code>int32 batchUnit = 4;</code>
     * @return The batchUnit.
     */
    @java.lang.Override
    public int getBatchUnit() {
      return batchUnit_;
    }

    public static final int BATCHID_FIELD_NUMBER = 5;
    private int batchId_;
    /**
     * <code>int32 batchId = 5;</code>
     * @return The batchId.
     */
    @java.lang.Override
    public int getBatchId() {
      return batchId_;
    }

    public static final int BATCHSIZE_FIELD_NUMBER = 6;
    private int batchSize_;
    /**
     * <code>int32 batchSize = 6;</code>
     * @return The batchSize.
     */
    @java.lang.Override
    public int getBatchSize() {
      return batchSize_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (rFWId_ != 0) {
        output.writeInt32(1, rFWId_);
      }
      if (benchType_ != 0) {
        output.writeInt32(2, benchType_);
      }
      if (workLoad_ != 0) {
        output.writeInt32(3, workLoad_);
      }
      if (batchUnit_ != 0) {
        output.writeInt32(4, batchUnit_);
      }
      if (batchId_ != 0) {
        output.writeInt32(5, batchId_);
      }
      if (batchSize_ != 0) {
        output.writeInt32(6, batchSize_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (rFWId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, rFWId_);
      }
      if (benchType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, benchType_);
      }
      if (workLoad_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, workLoad_);
      }
      if (batchUnit_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, batchUnit_);
      }
      if (batchId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, batchId_);
      }
      if (batchSize_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, batchSize_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof workload.WorkloadProto.clientRFW)) {
        return super.equals(obj);
      }
      workload.WorkloadProto.clientRFW other = (workload.WorkloadProto.clientRFW) obj;

      if (getRFWId()
          != other.getRFWId()) return false;
      if (getBenchType()
          != other.getBenchType()) return false;
      if (getWorkLoad()
          != other.getWorkLoad()) return false;
      if (getBatchUnit()
          != other.getBatchUnit()) return false;
      if (getBatchId()
          != other.getBatchId()) return false;
      if (getBatchSize()
          != other.getBatchSize()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RFWID_FIELD_NUMBER;
      hash = (53 * hash) + getRFWId();
      hash = (37 * hash) + BENCHTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getBenchType();
      hash = (37 * hash) + WORKLOAD_FIELD_NUMBER;
      hash = (53 * hash) + getWorkLoad();
      hash = (37 * hash) + BATCHUNIT_FIELD_NUMBER;
      hash = (53 * hash) + getBatchUnit();
      hash = (37 * hash) + BATCHID_FIELD_NUMBER;
      hash = (53 * hash) + getBatchId();
      hash = (37 * hash) + BATCHSIZE_FIELD_NUMBER;
      hash = (53 * hash) + getBatchSize();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static workload.WorkloadProto.clientRFW parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static workload.WorkloadProto.clientRFW parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static workload.WorkloadProto.clientRFW parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static workload.WorkloadProto.clientRFW parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static workload.WorkloadProto.clientRFW parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static workload.WorkloadProto.clientRFW parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static workload.WorkloadProto.clientRFW parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static workload.WorkloadProto.clientRFW parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static workload.WorkloadProto.clientRFW parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static workload.WorkloadProto.clientRFW parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static workload.WorkloadProto.clientRFW parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static workload.WorkloadProto.clientRFW parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(workload.WorkloadProto.clientRFW prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code java.clientRFW}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:java.clientRFW)
        workload.WorkloadProto.clientRFWOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return workload.WorkloadProto.internal_static_java_clientRFW_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return workload.WorkloadProto.internal_static_java_clientRFW_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                workload.WorkloadProto.clientRFW.class, workload.WorkloadProto.clientRFW.Builder.class);
      }

      // Construct using workload.WorkloadProto.clientRFW.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        rFWId_ = 0;

        benchType_ = 0;

        workLoad_ = 0;

        batchUnit_ = 0;

        batchId_ = 0;

        batchSize_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return workload.WorkloadProto.internal_static_java_clientRFW_descriptor;
      }

      @java.lang.Override
      public workload.WorkloadProto.clientRFW getDefaultInstanceForType() {
        return workload.WorkloadProto.clientRFW.getDefaultInstance();
      }

      @java.lang.Override
      public workload.WorkloadProto.clientRFW build() {
        workload.WorkloadProto.clientRFW result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public workload.WorkloadProto.clientRFW buildPartial() {
        workload.WorkloadProto.clientRFW result = new workload.WorkloadProto.clientRFW(this);
        result.rFWId_ = rFWId_;
        result.benchType_ = benchType_;
        result.workLoad_ = workLoad_;
        result.batchUnit_ = batchUnit_;
        result.batchId_ = batchId_;
        result.batchSize_ = batchSize_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof workload.WorkloadProto.clientRFW) {
          return mergeFrom((workload.WorkloadProto.clientRFW)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(workload.WorkloadProto.clientRFW other) {
        if (other == workload.WorkloadProto.clientRFW.getDefaultInstance()) return this;
        if (other.getRFWId() != 0) {
          setRFWId(other.getRFWId());
        }
        if (other.getBenchType() != 0) {
          setBenchType(other.getBenchType());
        }
        if (other.getWorkLoad() != 0) {
          setWorkLoad(other.getWorkLoad());
        }
        if (other.getBatchUnit() != 0) {
          setBatchUnit(other.getBatchUnit());
        }
        if (other.getBatchId() != 0) {
          setBatchId(other.getBatchId());
        }
        if (other.getBatchSize() != 0) {
          setBatchSize(other.getBatchSize());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        workload.WorkloadProto.clientRFW parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (workload.WorkloadProto.clientRFW) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int rFWId_ ;
      /**
       * <code>int32 RFWId = 1;</code>
       * @return The rFWId.
       */
      @java.lang.Override
      public int getRFWId() {
        return rFWId_;
      }
      /**
       * <code>int32 RFWId = 1;</code>
       * @param value The rFWId to set.
       * @return This builder for chaining.
       */
      public Builder setRFWId(int value) {
        
        rFWId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 RFWId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearRFWId() {
        
        rFWId_ = 0;
        onChanged();
        return this;
      }

      private int benchType_ ;
      /**
       * <code>int32 benchType = 2;</code>
       * @return The benchType.
       */
      @java.lang.Override
      public int getBenchType() {
        return benchType_;
      }
      /**
       * <code>int32 benchType = 2;</code>
       * @param value The benchType to set.
       * @return This builder for chaining.
       */
      public Builder setBenchType(int value) {
        
        benchType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 benchType = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearBenchType() {
        
        benchType_ = 0;
        onChanged();
        return this;
      }

      private int workLoad_ ;
      /**
       * <code>int32 workLoad = 3;</code>
       * @return The workLoad.
       */
      @java.lang.Override
      public int getWorkLoad() {
        return workLoad_;
      }
      /**
       * <code>int32 workLoad = 3;</code>
       * @param value The workLoad to set.
       * @return This builder for chaining.
       */
      public Builder setWorkLoad(int value) {
        
        workLoad_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 workLoad = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearWorkLoad() {
        
        workLoad_ = 0;
        onChanged();
        return this;
      }

      private int batchUnit_ ;
      /**
       * <code>int32 batchUnit = 4;</code>
       * @return The batchUnit.
       */
      @java.lang.Override
      public int getBatchUnit() {
        return batchUnit_;
      }
      /**
       * <code>int32 batchUnit = 4;</code>
       * @param value The batchUnit to set.
       * @return This builder for chaining.
       */
      public Builder setBatchUnit(int value) {
        
        batchUnit_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 batchUnit = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearBatchUnit() {
        
        batchUnit_ = 0;
        onChanged();
        return this;
      }

      private int batchId_ ;
      /**
       * <code>int32 batchId = 5;</code>
       * @return The batchId.
       */
      @java.lang.Override
      public int getBatchId() {
        return batchId_;
      }
      /**
       * <code>int32 batchId = 5;</code>
       * @param value The batchId to set.
       * @return This builder for chaining.
       */
      public Builder setBatchId(int value) {
        
        batchId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 batchId = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearBatchId() {
        
        batchId_ = 0;
        onChanged();
        return this;
      }

      private int batchSize_ ;
      /**
       * <code>int32 batchSize = 6;</code>
       * @return The batchSize.
       */
      @java.lang.Override
      public int getBatchSize() {
        return batchSize_;
      }
      /**
       * <code>int32 batchSize = 6;</code>
       * @param value The batchSize to set.
       * @return This builder for chaining.
       */
      public Builder setBatchSize(int value) {
        
        batchSize_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 batchSize = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearBatchSize() {
        
        batchSize_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:java.clientRFW)
    }

    // @@protoc_insertion_point(class_scope:java.clientRFW)
    private static final workload.WorkloadProto.clientRFW DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new workload.WorkloadProto.clientRFW();
    }

    public static workload.WorkloadProto.clientRFW getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<clientRFW>
        PARSER = new com.google.protobuf.AbstractParser<clientRFW>() {
      @java.lang.Override
      public clientRFW parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new clientRFW(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<clientRFW> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<clientRFW> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public workload.WorkloadProto.clientRFW getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface serverRFDOrBuilder extends
      // @@protoc_insertion_point(interface_extends:java.serverRFD)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 RFWId = 1;</code>
     * @return The rFWId.
     */
    int getRFWId();

    /**
     * <code>int32 lastBatchId = 2;</code>
     * @return The lastBatchId.
     */
    int getLastBatchId();

    /**
     * <code>repeated string item = 3;</code>
     * @return A list containing the item.
     */
    java.util.List<java.lang.String>
        getItemList();
    /**
     * <code>repeated string item = 3;</code>
     * @return The count of item.
     */
    int getItemCount();
    /**
     * <code>repeated string item = 3;</code>
     * @param index The index of the element to return.
     * @return The item at the given index.
     */
    java.lang.String getItem(int index);
    /**
     * <code>repeated string item = 3;</code>
     * @param index The index of the value to return.
     * @return The bytes of the item at the given index.
     */
    com.google.protobuf.ByteString
        getItemBytes(int index);
  }
  /**
   * Protobuf type {@code java.serverRFD}
   */
  public static final class serverRFD extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:java.serverRFD)
      serverRFDOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use serverRFD.newBuilder() to construct.
    private serverRFD(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private serverRFD() {
      item_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new serverRFD();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private serverRFD(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              rFWId_ = input.readInt32();
              break;
            }
            case 16: {

              lastBatchId_ = input.readInt32();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                item_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              item_.add(s);
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          item_ = item_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return workload.WorkloadProto.internal_static_java_serverRFD_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return workload.WorkloadProto.internal_static_java_serverRFD_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              workload.WorkloadProto.serverRFD.class, workload.WorkloadProto.serverRFD.Builder.class);
    }

    public static final int RFWID_FIELD_NUMBER = 1;
    private int rFWId_;
    /**
     * <code>int32 RFWId = 1;</code>
     * @return The rFWId.
     */
    @java.lang.Override
    public int getRFWId() {
      return rFWId_;
    }

    public static final int LASTBATCHID_FIELD_NUMBER = 2;
    private int lastBatchId_;
    /**
     * <code>int32 lastBatchId = 2;</code>
     * @return The lastBatchId.
     */
    @java.lang.Override
    public int getLastBatchId() {
      return lastBatchId_;
    }

    public static final int ITEM_FIELD_NUMBER = 3;
    private com.google.protobuf.LazyStringList item_;
    /**
     * <code>repeated string item = 3;</code>
     * @return A list containing the item.
     */
    public com.google.protobuf.ProtocolStringList
        getItemList() {
      return item_;
    }
    /**
     * <code>repeated string item = 3;</code>
     * @return The count of item.
     */
    public int getItemCount() {
      return item_.size();
    }
    /**
     * <code>repeated string item = 3;</code>
     * @param index The index of the element to return.
     * @return The item at the given index.
     */
    public java.lang.String getItem(int index) {
      return item_.get(index);
    }
    /**
     * <code>repeated string item = 3;</code>
     * @param index The index of the value to return.
     * @return The bytes of the item at the given index.
     */
    public com.google.protobuf.ByteString
        getItemBytes(int index) {
      return item_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (rFWId_ != 0) {
        output.writeInt32(1, rFWId_);
      }
      if (lastBatchId_ != 0) {
        output.writeInt32(2, lastBatchId_);
      }
      for (int i = 0; i < item_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, item_.getRaw(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (rFWId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, rFWId_);
      }
      if (lastBatchId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, lastBatchId_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < item_.size(); i++) {
          dataSize += computeStringSizeNoTag(item_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getItemList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof workload.WorkloadProto.serverRFD)) {
        return super.equals(obj);
      }
      workload.WorkloadProto.serverRFD other = (workload.WorkloadProto.serverRFD) obj;

      if (getRFWId()
          != other.getRFWId()) return false;
      if (getLastBatchId()
          != other.getLastBatchId()) return false;
      if (!getItemList()
          .equals(other.getItemList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RFWID_FIELD_NUMBER;
      hash = (53 * hash) + getRFWId();
      hash = (37 * hash) + LASTBATCHID_FIELD_NUMBER;
      hash = (53 * hash) + getLastBatchId();
      if (getItemCount() > 0) {
        hash = (37 * hash) + ITEM_FIELD_NUMBER;
        hash = (53 * hash) + getItemList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static workload.WorkloadProto.serverRFD parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static workload.WorkloadProto.serverRFD parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static workload.WorkloadProto.serverRFD parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static workload.WorkloadProto.serverRFD parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static workload.WorkloadProto.serverRFD parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static workload.WorkloadProto.serverRFD parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static workload.WorkloadProto.serverRFD parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static workload.WorkloadProto.serverRFD parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static workload.WorkloadProto.serverRFD parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static workload.WorkloadProto.serverRFD parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static workload.WorkloadProto.serverRFD parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static workload.WorkloadProto.serverRFD parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(workload.WorkloadProto.serverRFD prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code java.serverRFD}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:java.serverRFD)
        workload.WorkloadProto.serverRFDOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return workload.WorkloadProto.internal_static_java_serverRFD_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return workload.WorkloadProto.internal_static_java_serverRFD_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                workload.WorkloadProto.serverRFD.class, workload.WorkloadProto.serverRFD.Builder.class);
      }

      // Construct using workload.WorkloadProto.serverRFD.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        rFWId_ = 0;

        lastBatchId_ = 0;

        item_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return workload.WorkloadProto.internal_static_java_serverRFD_descriptor;
      }

      @java.lang.Override
      public workload.WorkloadProto.serverRFD getDefaultInstanceForType() {
        return workload.WorkloadProto.serverRFD.getDefaultInstance();
      }

      @java.lang.Override
      public workload.WorkloadProto.serverRFD build() {
        workload.WorkloadProto.serverRFD result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public workload.WorkloadProto.serverRFD buildPartial() {
        workload.WorkloadProto.serverRFD result = new workload.WorkloadProto.serverRFD(this);
        int from_bitField0_ = bitField0_;
        result.rFWId_ = rFWId_;
        result.lastBatchId_ = lastBatchId_;
        if (((bitField0_ & 0x00000001) != 0)) {
          item_ = item_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.item_ = item_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof workload.WorkloadProto.serverRFD) {
          return mergeFrom((workload.WorkloadProto.serverRFD)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(workload.WorkloadProto.serverRFD other) {
        if (other == workload.WorkloadProto.serverRFD.getDefaultInstance()) return this;
        if (other.getRFWId() != 0) {
          setRFWId(other.getRFWId());
        }
        if (other.getLastBatchId() != 0) {
          setLastBatchId(other.getLastBatchId());
        }
        if (!other.item_.isEmpty()) {
          if (item_.isEmpty()) {
            item_ = other.item_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureItemIsMutable();
            item_.addAll(other.item_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        workload.WorkloadProto.serverRFD parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (workload.WorkloadProto.serverRFD) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int rFWId_ ;
      /**
       * <code>int32 RFWId = 1;</code>
       * @return The rFWId.
       */
      @java.lang.Override
      public int getRFWId() {
        return rFWId_;
      }
      /**
       * <code>int32 RFWId = 1;</code>
       * @param value The rFWId to set.
       * @return This builder for chaining.
       */
      public Builder setRFWId(int value) {
        
        rFWId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 RFWId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearRFWId() {
        
        rFWId_ = 0;
        onChanged();
        return this;
      }

      private int lastBatchId_ ;
      /**
       * <code>int32 lastBatchId = 2;</code>
       * @return The lastBatchId.
       */
      @java.lang.Override
      public int getLastBatchId() {
        return lastBatchId_;
      }
      /**
       * <code>int32 lastBatchId = 2;</code>
       * @param value The lastBatchId to set.
       * @return This builder for chaining.
       */
      public Builder setLastBatchId(int value) {
        
        lastBatchId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 lastBatchId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearLastBatchId() {
        
        lastBatchId_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList item_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureItemIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          item_ = new com.google.protobuf.LazyStringArrayList(item_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated string item = 3;</code>
       * @return A list containing the item.
       */
      public com.google.protobuf.ProtocolStringList
          getItemList() {
        return item_.getUnmodifiableView();
      }
      /**
       * <code>repeated string item = 3;</code>
       * @return The count of item.
       */
      public int getItemCount() {
        return item_.size();
      }
      /**
       * <code>repeated string item = 3;</code>
       * @param index The index of the element to return.
       * @return The item at the given index.
       */
      public java.lang.String getItem(int index) {
        return item_.get(index);
      }
      /**
       * <code>repeated string item = 3;</code>
       * @param index The index of the value to return.
       * @return The bytes of the item at the given index.
       */
      public com.google.protobuf.ByteString
          getItemBytes(int index) {
        return item_.getByteString(index);
      }
      /**
       * <code>repeated string item = 3;</code>
       * @param index The index to set the value at.
       * @param value The item to set.
       * @return This builder for chaining.
       */
      public Builder setItem(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureItemIsMutable();
        item_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string item = 3;</code>
       * @param value The item to add.
       * @return This builder for chaining.
       */
      public Builder addItem(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureItemIsMutable();
        item_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string item = 3;</code>
       * @param values The item to add.
       * @return This builder for chaining.
       */
      public Builder addAllItem(
          java.lang.Iterable<java.lang.String> values) {
        ensureItemIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, item_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string item = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearItem() {
        item_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string item = 3;</code>
       * @param value The bytes of the item to add.
       * @return This builder for chaining.
       */
      public Builder addItemBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureItemIsMutable();
        item_.add(value);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:java.serverRFD)
    }

    // @@protoc_insertion_point(class_scope:java.serverRFD)
    private static final workload.WorkloadProto.serverRFD DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new workload.WorkloadProto.serverRFD();
    }

    public static workload.WorkloadProto.serverRFD getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<serverRFD>
        PARSER = new com.google.protobuf.AbstractParser<serverRFD>() {
      @java.lang.Override
      public serverRFD parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new serverRFD(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<serverRFD> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<serverRFD> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public workload.WorkloadProto.serverRFD getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_java_clientRFW_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_java_clientRFW_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_java_serverRFD_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_java_serverRFD_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n!main/java/workload/Workload.proto\022\004jav" +
      "a\"v\n\tclientRFW\022\r\n\005RFWId\030\001 \001(\005\022\021\n\tbenchTy" +
      "pe\030\002 \001(\005\022\020\n\010workLoad\030\003 \001(\005\022\021\n\tbatchUnit\030" +
      "\004 \001(\005\022\017\n\007batchId\030\005 \001(\005\022\021\n\tbatchSize\030\006 \001(" +
      "\005\"=\n\tserverRFD\022\r\n\005RFWId\030\001 \001(\005\022\023\n\013lastBat" +
      "chId\030\002 \001(\005\022\014\n\004item\030\003 \003(\tB\031\n\010workloadB\rWo" +
      "rkloadProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_java_clientRFW_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_java_clientRFW_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_java_clientRFW_descriptor,
        new java.lang.String[] { "RFWId", "BenchType", "WorkLoad", "BatchUnit", "BatchId", "BatchSize", });
    internal_static_java_serverRFD_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_java_serverRFD_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_java_serverRFD_descriptor,
        new java.lang.String[] { "RFWId", "LastBatchId", "Item", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
